#!/usr/bin/python
import os
import sys
import argparse
import glob
import sqlite3

parser = argparse.ArgumentParser(description='print Firefox histories')
parser.add_argument('num_records', metavar='N', type=int, nargs=1,
                    help='number of records')
parser.add_argument('-e', '--excludeurl', metavar='PATTERN', action='append',
                    help='exclude URLs which matches to PATTERN')
parser.add_argument('-d', '--dedupe', action='store_true',
                    help='dedupe results')
args = parser.parse_args()

dbfile_ptn = '~/.mozilla/firefox/*.default/places.sqlite'
dbfile = glob.glob(os.path.expanduser(dbfile_ptn));
if not dbfile:
    sys.stderr.write('database not found')
    sys.exit(1)

con = sqlite3.connect(dbfile[0])
cur = con.cursor()

sql = 'SELECT'
if args.dedupe:
    sql += ' DISTINCT'
sql += ' p.title, p.url FROM moz_historyvisits AS h INNER JOIN moz_places AS p ON h.place_id = p.id'
if args.excludeurl:
    sql += ' WHERE' + ' AND'.join([' p.url NOT LIKE ?' for i in xrange(len(args.excludeurl))])
sql += ' ORDER BY h.id DESC LIMIT ?'
cur.execute(sql, tuple(args.excludeurl or ()) + (args.num_records[0],))

for row in cur:
    print ((row[0] or '') + ' / ' + row[1]).encode('utf-8')

con.close()
